# Generated by Django 3.2.4 on 2022-01-20 11:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('crudd', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='employee',
            name='Phone',
            field=models.CharField(max_length=10),
        ),
    ]
